module.exports = {

  FETCH_TRENDS: 'FETCH_TRENDS',
  RECEIVE_TRENDS: 'RECEIVE_TRENDS',

  FETCH_TWEETS: 'FETCH_TWEETS',
  RECEIVE_TWEETS: 'RECEIVE_TWEETS',

  SELECT_TWEET: 'SELECT_TWEET',

  TOGGLE_FILTERS: 'TOGGLE_FILTERS',
  CHANGE_COUNT: 'CHANGE_COUNT',
  CHANGE_FILTER: 'CHANGE_FILTER',


}
